server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway

eureka:
   client:
     service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
     instance-id: getaway-9527.com
     prefer-ip-address: true

zuul:
  routes:
    mydept:
      path: /mydept/**
      service-id: microservice-dept
  ignored-services: "*"
  prefix: /meta

info:
  app.name: meta-microservice
  company.name: www.meta.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$


